version: '3.4'

services:
  expogan.web:
    image: ${DOCKER_REGISTRY-}expogan-web
    build:
      context: .
      dockerfile: src/web/ExpoGAN.Web/Dockerfile
    ports:
      - "7000:80"
      - "7001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data:/app/wwwroot/data
    depends_on:
      - expogan.api
      - expogan.data
    networks:
      - expogan

  expogan.api:
    image: ${DOCKER_REGISTRY-}expogan-api
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./data:/app/data
    depends_on:
      - expogan.data
    networks:
      - expogan

  expogan.data:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - expogan

  expogan.adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=expogan.data
    depends_on:
      - expogan.data
    networks:
      - expogan

volumes:
  #data:
  database-data:

networks:
  expogan: